### ISSUE TITLE
com.codeaffine.eclipse.swt.test.util exports packages without version

### ISSUE THREAD

**Issue by rherrmann** [fappel/xiliary#65]
The packages that are exported by `com.codeaffine.eclipse.swt.test.util` are unversioned. Seemingly, older versions of this bundle did specify version information and thus my Import-Package directives now fail to work.

Example:
```
Import-Package:  com.codeaffine.eclipse.swt.test.util;version="[0.1.0,1.0.0)",
...
```

**Comment by fappel** [comment]
After given this a second thought I decided to keep it as it is. This is because the swt.test.util doesn't provide any implementations of API's that are exchangeable with implementations of other vendors. So, IMHO it is no disadvantage here to use bundle dependencies, quite the contrary considering once the bundle would export more than one package. The latter would make using package imports more bloating for no good reasons.
