### ISSUE TITLE
[CleanSheet] Neon - When switching to the theme, AER reports an error

### ISSUE THREAD

**Issue by Treehopper** [fappel/xiliary#79]
The message is:
CSS property 'unselected-hot-tab-color-background' has been deprecated: renamed as swt-unselected-hot-tab-color-background

**Comment by abelhegedus** [comment]
I have the same in my log on Oxygen

```
eclipse.buildId=4.7.0.I20161208-0830
java.version=1.8.0_121
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en_GB
Framework arguments:  -product org.eclipse.epp.package.committers.product
Command-line arguments:  -os win32 -ws win32 -arch x86_64 -product org.eclipse.epp.package.committers.product

org.eclipse.e4.ui.css.core
Error
Mon Mar 20 16:55:35 CET 2017
CSS property 'unselected-hot-tab-color-background' has been deprecated: renamed as swt-unselected-hot-tab-color-background
```

**Comment by fappel** [comment]
Thanks for reporting this problem. Unfortunately, there isn't much I can do about it at the moment since changing the CSS property to the current theme would drop Luna backward compatibility. However, I might drop the support for Luna with the upcoming Oxygen release and switch to the correct CSS property setting.

**Comment by Treehopper** [comment]
> However, I might drop the support for Luna with the upcoming Oxygen release and switch to the correct CSS property setting.

That would work for me. Thanks!
