### ISSUE TITLE
StyleText rendering issue with the FlatScrollBar

### ISSUE THREAD

**Issue by gayanper** [fappel/xiliary#87]
When the FlatScrollBar is used with the StyledText the last line is not rendered properly. This is really prominent when the scroll bar width is set to **fixed**. The line number is not shown at all and source line is rendered partially as in the below picture

![image](https://user-images.githubusercontent.com/7471994/34659820-5c1156be-f463-11e7-99da-e3c92a4c9c77.png)

**Comment by fappel** [comment]
Thanks for reporting this isssue. I will have a look at it ASAP

**Comment by PyvesB** [comment]
I'm seeing this issue as well. The missing line number is particularly annoying/visible.

Using the E4 CSS spy, you can see that the ruler ends "early", and has a smaller height than that of the parent canvas or the adjacent styled text:
![Screenshot (183)](https://user-images.githubusercontent.com/10694593/81503418-d0691300-92e3-11ea-9dc1-4395ed3a7283.png)

The little black box circled in the above screenshot (where line number 208 should have been) is not part of the ruler nor the styled text, it's some sort of empty zone from the parent canvas, which also makes it hard to style properly.

Another interesting observation: [DevStyle](https://marketplace.eclipse.org/content/darkest-dark-theme-devstyle), which uses Xiliary underneath the hood does not have this ruler problem:
![Screenshot (184)](https://user-images.githubusercontent.com/10694593/81503548-7c126300-92e4-11ea-9bfb-0f84b54481f7.png)

I went digging into the Xiliary source code shipped with DevStyle and did not spot any code changes that deal with this particular problem (even though the rest of their source is proprietary, as mandated by Xiliary's EPL they've disclosed at least part of the modified source code in the distributed bundles).

However, using CSS Spy again, I noticed that they were using "dual" styling of scroll bars on the styled text:
````
flat-scroll-bar: true;
flat-scroll-bar-thumb: rgb(125, 125, 125);
flat-scroll-bar-page-increment: rgb(217, 217, 217);
swt-scrollbar-themed: true;
swt-scrollbar-background-color: rgb(227, 227, 227);
swt-scrollbar-foreground-color: rgb(212, 212, 212);
swt-scrollbar-width: 4.0px;
swt-scrollbar-border-radius: 4.0px;
swt-scrollbar-mouse-near-scroll-width: 15.0px;
````

They are applying Xiliary's custom scrollbars + Eclipse's custom srollbars (the latter were phased out a few days ago in https://git.eclipse.org/r/c/161336; Eclipse itself only used them for the dark theme and now invokes native dark theme capabilities on the various operating systems instead).

So something in Eclipse's old custom scrollbar approach is properly synchronising the ruler and styled text heights. I did some digging, but have not been able to crack the problem so far. Lack of familiarity with this project's code and SWT's internal are probably to blame.

@fappel does the above analysis help? Would love to see this fixed! :)

**Comment by fappel** [comment]
Actually, I remember I did have a look at this bug - well - probably a few years ago. Unfortunately, I did not take any notes. But I'm pretty sure the problem with this one is the size of the original scroll bar.

As you have noticed without a doubt, the approach I took with the FlatScrollBar adapters was to reparent the original component to an adapter composite, use this adapter within the widget tree instead of the original component, increase the size of the original component so much that the the underlying window scrollbars get hidden by the overlays containing the FlatScrollBar instances. The rest was a bit of synchronizing the scrollbar states and a lot of praying that I get away with it most of the time. Which I did to my own surprise.

However, there are limits to this approach. In particular, when the UI code uses references to the StyleText, Tree, Table for layout calculations. Most of the trouble could be handled with layout reconciliation done within the class [LayoutReconciliation](https://github.com/fappel/xiliary/blob/development/com.codeaffine.eclipse.swt/src/com/codeaffine/eclipse/swt/widget/scrollable/context/LayoutReconciliation.java). Obviously, this only works with a set of hardcoded trouble makers.

With this in mind, I'm pretty sure the height calculation of the ruler takes the height of the original horizontal scrollbar of the StyledText component into account somehow like this: height of styled text adapter minus the height which the horizontal scrollbar of the style text would consume. This leads to the ugly gap. If I remember correctly the catch is, that the layout problem does not reside within the adapter but causes some problems in the outside world. Fixing such problems means dealing with inside knowledge on the implementation of the trouble making stuff. The solution of the rendering problems of the "org.eclipse.ui.part.PageBook" section gives a little taste of what I am talking about - ugly, ugly, ugly. Well, the road to hell is plaid with good intentions ;-)

The now phased out eclipse scroll bar manipulation seems to draw the editor scrollbars manually. As this solution is implemented within the eclipse theming layer it could be possible to hide the original scrollbars at creation time. This might explain, how this approach gets rid of the superfluous height measure. But this is just a wild guess and would need more digging. Might be solved completely differently.

So far my five cents on this. I'm pretty busy currently, so I can't promise that I find the time to look deeper in this soon.
